# Generated by Django 4.1.5 on 2023-01-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_product_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_moderated', 'Может moderated статус')]},
        ),
    ]
